### PR TITLE
feature: Add concent

### PR DESCRIPTION
**Pull request by fantasticsoul**
Add concent implement

### CODE REVIEW

**Comment by dai-shi** [comment]
Would you try removing `- 10` in .travis.yml?

**Comment by dai-shi** [comment]
The master branch is updated.

**Comment by fantasticsoul** [comment]
I have merged the latest code of master branch

**Comment by fantasticsoul** [comment]
Hey, dude,  everything is ok now, can you accept my PR?

**Comment by dai-shi** [comment]
We have some notes in this thread: https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode/pull/36#issuecomment-829644387

What is your result like?

(Also, I need to follow up latest React experimental build, which turns out breaking change, so until it's fixed, no PRs should be merged to avoid further work on me. I feel like dropping some existing libs before working on it.)

**Comment by dai-shi** [comment]
Let me close this as we dropped many in #42. Feel free to work on your fork and share the result in https://github.com/dai-shi/lets-compare-global-state-with-react-hooks

**Pull request closed without merging**
