### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by josepot**
Just making sure that the README is up to date :slightly_smiling_face:

### CODE REVIEW

**Review by dai-shi — COMMENTED** [review]
hmm, i don't think jotai changes any behaviors lately. let me run on my end. tests might not be very stable? anyway merging this.

**Comment by josepot** [comment]
> hmm, i don't think jotai changes any behaviors lately. let me run on my end. tests might not be very stable? anyway merging this.

I really have no idea TBH :grimacing: I actually didn't notice this until I read your comment. I just updated the dependencies because I was almost certain that the latest version of `@react-rxjs/core` should have better support for concurrent-rendering and then I ran the results on my machine and these are the results that I got :shrug:

Although, I just re-run the tests just for `jotai` and `jotai-versioned-write` on my machine and this is what I got:

```sh
jotai                                                
  With useTransition                                 
    Level 1                                          
      ✓ No tearing finally on update (6446 ms)       
      ✓ No tearing finally on mount (13298 ms)
    Level 2         
      ✓ No tearing temporarily on update (9503 ms)
      ✕ No tearing temporarily on mount (11270 ms)   
    Level 3                                          
      ✓ Can interrupt render (time slicing) (4517 ms)
      ✕ Can branch state (wip state) (11009 ms)      
  With useDeferredValue                              
    Level 1                                          
      ✓ No tearing finally on update (16284 ms)      
      ✓ No tearing finally on mount (12298 ms)       
    Level 2                                          
      ✓ No tearing temporarily on update (20350 ms)  
      ✕ No tearing temporarily on mount (12248 ms)   
jotai-versioned-write                                
  With useTransition                             
    Level 1                                          
      ✓ No tearing finally on update (5437 ms)   
      ✓ No tearing finally on mount (10324 ms)       
    Level 2                                          
      ✓ No tearing temporarily on update (9514 ms)   
      ✓ No tearing temporarily on mount (9282 ms)    
    Level 3                                          
      ✓ Can interrupt render (time slicing) (4504 ms)
      ✕ Can branch state (wip state) (16055 ms)
  With useDeferredValue
    Level 1                                          
      ✓ No tearing finally on update (11331 ms)      
      ✓ No tearing finally on mount (6527 ms)        
    Level 2                                          
      ✓ No tearing temporarily on update (15431 ms)  
      ✓ No tearing temporarily on mount (6428 ms)    
```

So, yeah, there must a test that's not very stable...

**Comment by josepot** [comment]
Now that I think about it, while the tests were running there was a moment when my computer started entering on "Suspended" mode and as soon as I noticed I started moving the mouse to stop it... I thought that I had stopped it in time, but perhaps that messed up with one of the tests, if that's the case I'm terribly sorry. I really hope that you believe me when I tell you that I didn't mean to make Jotai look bad, and that was an honest accident :pray:

**Comment by dai-shi** [comment]
No worries!

I found the failure in jotai-versioned-write is stable and noticed there's a regression in v1.6.0. I will look into it.

**Pull request merged**
