### PR TITLE
Added agile-ts

### PR DESCRIPTION
**Pull request by bennodev19**
I added [AgileTs](https://agile-ts.org).

### CODE REVIEW

**Comment by dai-shi** [comment]
Nice try!
As I can't keep everything on my end, I started removing some libraries.
Let me leave this PR unmerged for now. I'll leave it open for a while.
For listing purpose, I made another repo. Please take a look if you are interested.
https://github.com/dai-shi/lets-compare-global-state-with-react-hooks

**Comment by bennodev19** [comment]
Perhaps you should mention in your readme 
that State Manager added by a third person/party aren't desired.
Anyway, it was definitely interesting to find out something about the 'Concurrent Mode' ^^
thanks :D

**Comment by dai-shi** [comment]
> Perhaps you should mention in your readme

Good idea. Thanks for the suggestion!

**Comment by dai-shi** [comment]
done. bb790fb

**Comment by dai-shi** [comment]
Let me close this. Feel free to work on your fork. Questions/suggestions are welcome.

**Pull request closed without merging**
