### PR TITLE
feat: add react-query

### PR DESCRIPTION
**Pull request by TkDodo**
@dai-shi I'm adding react-query here, but for some reason, I can't run the test suites. I'm getting the following error:

```
/bin/sh: http-server: command not found
Process finished with exit code 127
```

anyhow, I opened the app locally and one thing I noticed is that `increment count in transition` doesn't seem to work. The `main` counter gets incremented immediately, while the other counters take a bit of time:

screencast 2022-04-19 11-19-11

`zustand` behaves differently. Is this an issue in react-query?

### CODE REVIEW

**Comment by dai-shi** [comment]
> /bin/sh: http-server: command not found

Is this shown when you run `yarn run http-server`? How about `npx http-server dist`?
Looks like it's missing in README.

**Comment by dai-shi** [comment]
> Is this an issue in react-query?

I'm not sure if it's an issue or just a behavior. Because RQ is promise based, it can behave differently.

**Comment by TkDodo** [comment]
> Is this shown when you run yarn run http-server? How about npx http-server dist?

never mind me, I was trying to run the tests in my IDE. everything works when running the test command 👍 

Test result was the following for me now:

```
  react-query
    With useTransition
      Level 1
        ✓ No tearing finally on update (8010 ms)
        ✓ No tearing finally on mount (4578 ms)
      Level 2
        ✕ No tearing temporarily on update (12952 ms)
        ✓ No tearing temporarily on mount (4496 ms)
      Level 3
        ✕ Can interrupt render (time slicing) (8285 ms)
        ✕ Can branch state (wip state) (6615 ms)
    With useDeferredValue
      Level 1
        ✓ No tearing finally on update (9486 ms)
        ✓ No tearing finally on mount (4527 ms)
      Level 2
        ✓ No tearing temporarily on update (13615 ms)
        ✓ No tearing temporarily on mount (4478 ms)
```

I think level two, temporary tearing is the issue I was showing with the gif?

**Comment by dai-shi** [comment]
Yeah. It doesn't tear within child components, but it tears from `Main` component. Such temporarily tearing is not an issue at all for most RQ apps though.

**Comment by TkDodo** [comment]
I added the results to the readme. would love to know what I can do to investigate this temporary tearing on update though, as not other lib seems to have it 🤷 . For now, we can merge this if you agree :)

**Review by dai-shi — APPROVED** [review]
Sorry for the delay.

**Pull request merged**
